### ISSUE TITLE
Code is highlighted in all red

### ISSUE THREAD

**Issue by lbrandt** [quarto-dev/quarto#505] opened 2024-08-03 12:18 UTC
Type: <b>Bug</b>

After a restart, all Quarto document code is highlighted in all red. Diagnosed through VS Code bisect.

Extension version: 1.113.0
VS Code version: Code 1.92.0 (Universal) (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Pro (11 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|18.00GB (1.46GB free)|
|Process Argv|--crash-reporter-id 07349579-7bb9-4cad-b867-0972081e0bcb|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
refactort:31108082
ccplti:31103428
pythonrstrctxtcf:31103194
wkspc-onlycs-c:31106320

```

</details>

**Comment by driftwoods** [comment] 2024-08-03 15:19
I can confirm the the same issue occurs in vscode version 1.92 under both windows 11 and Fedora Linux 39. If the same .qmd file is renamed to .md file, hightlighting color is back to normal.

This same issue was reported to the vscode github project, and it is marked as "caused by extension".
https://github.com/microsoft/vscode/issues/224627

**Comment by josuem** [comment] 2024-08-04 19:33
A temporary solution is to downgrade to VS Code 1.91.1. I tested it on Windows 11, and it worked.

https://github.com/quarto-dev/quarto/issues/501#issuecomment-2265183380

**Comment by mcanouil** [comment] 2024-08-05 11:04
Duplicate of #501

**Closed** 2024-08-06 23:12 UTC
