### ISSUE TITLE
Corrupted color scheme for qmd files in vscode editor after updating the vscode

### ISSUE THREAD

**Issue by hurak** [quarto-dev/quarto#504] opened 2024-08-03 08:57 UTC
With vscode Extension for Quarto v1.113.0, Quarto v1.6.4, and vscode v1.92.0, I have recently started experiencing weird colouring of the qmd source code. I am not aware of any change in the setting. Perhaps the only possible culprit that I can think of is the update of the vscode itself (the latest version is from July 31, the automatic update probably happened on August 1, which agrees with the time I started having the problems).

The problem is best illustrated by screenshots. In the following screenshot, the standard behaviour is shown:
<img width="818" alt="Snímek obrazovky 2024-08-03 v 10 42 34" src="https://github.com/user-attachments/assets/e5702c37-3826-4594-b079-9b4fceb504f6">

But in the following screenshot, as soon as I add whatever other line to the header besides the title, the colouring of the text changes immediately in an undesirable way (for more complex text it is obvious that vscode does not recognise the qmd syntax):
<img width="818" alt="Snímek obrazovky 2024-08-03 v 10 42 12" src="https://github.com/user-attachments/assets/40d42033-e538-49d6-947f-9a6277057702">

**Comment by danmackinlay** [comment] 2024-08-05 00:48
looks like it might duplicate #501

**Comment by mcanouil** [comment] 2024-08-05 11:04
Indeed.

Duplicate of #501

**Closed** 2024-08-06 23:12 UTC
