### ISSUE TITLE
Quarto citation autocomplete in VS Code has stopped working and pandoc process consumes high usage

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto#410] opened 2024-04-11 08:32 UTC
Hi, I also want to point out that Quarto citation autocomplete in VS Code has stopped working.
Furthermore, I have not found a way to disable this citation autocomplete feature, and the pandoc underlying process runs indefinitely consuming a high amount of RAM and CPU. The only way for me to fix this is to kill the pandoc process every time I (accidentally) ask for citation autocompletion.

_Originally posted by @DedZago in https://github.com/quarto-dev/quarto-cli/discussions/1639#discussioncomment-9080478_

**Comment by mcanouil** [comment] 2024-04-11 08:36
FYI, on macOS with the latest version of everything, I don't see any issues.
<img width="1624" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/ded21a65-dfa3-45e4-a423-c6a54c9f7cb4">

**Comment by cderv** [comment] 2024-04-11 10:28
Possibly related: 
* https://github.com/quarto-dev/quarto-cli/issues/9315

**Comment by cscheid** [comment] 2024-04-19 22:21
I'd love to have a repro to make sure we found it, but I think https://github.com/quarto-dev/quarto-cli/pull/9428 will close this.

**Comment by cscheid** [comment] 2024-04-20 17:45
I'm going to go ahead and close this because I think https://github.com/quarto-dev/quarto-cli/pull/9428 does actually resolve the problem. If it persists and y'all find a reproducible example, please reopen it. Thanks!

**Closed by cscheid** 2024-04-20 17:45 UTC
