### ISSUE TITLE
Error: Request textDocument/completion failed

### ISSUE THREAD

**Issue by jooyoungseo** [quarto-dev/quarto#212] opened 2023-07-06 03:11 UTC
This issue may have to do with the Quarto cli, but I am filing issue here first.

When the latest quarto prerelease is used with VSCode on Windows 11, `@` sign does not trigger auto-completion:

![VSCode error and developer pane](https://github.com/quarto-dev/quarto/assets/19754711/83797274-8448-4102-99b6-5bba17d416ee)

This issue does not happen with the stable Quarto cli.

**Comment by cscheid** [comment] 2023-07-06 10:07
Can you provide the document where this happens? It's likely another crossref regression which I need to track down and fix (we now have unit tests for this general issue in `quarto-cli`, but I think you have evidence that we're not catching everything).

**Comment by jooyoungseo** [comment] 2023-07-06 13:37
This issue happens with any qmd documents on my end. I am not sure whether this is a Windows-specific issue though.

**Comment by cscheid** [comment] 2023-07-06 13:50
I can't reproduce on macOS, vscode, and latest `quarto`:

<img width="1237" alt="screenshot of vs code with crossref being resolved successfully on dropdown menu" src="https://github.com/quarto-dev/quarto/assets/285675/9900345c-34be-4af1-b874-c8691feae810">

**Comment by jjallaire** [comment] 2023-07-06 13:54
I reproduced a different problem on Windows that requires the following conditions:

(1) A bibliography is present; and

(2) Running in Parallels such that UNC paths are in play.

@jooyoungseo Does this document have a bibliography? What happens if you remove it?

BTW you can find error messages by switching to the Output tab (alongside Terminal) and then selecting "Quarto LSP"

**Comment by cscheid** [comment] 2023-07-06 14:19
Update: I can repro this issue locally. I'll take a look today.

**Comment by jjallaire** [comment] 2023-07-06 14:25
Update from my end, the error I was seeing is exclusive to projects with UNC paths (which aren't supported in other ways). @cscheid glad you got a repro!

**Comment by jooyoungseo** [comment] 2023-07-06 14:35
@jjallaire -- Yes, actually I had saved my project on Box Drive. It's interesting because the auto-completion works only with the stable version not with pre-release. Yes, the bibliography file exists and it's defined in the YAML. I have shared my private project with @cscheid for further investigation.

**Comment by jjallaire** [comment] 2023-07-07 11:22
@cscheid LMK if there might be an issue w/ the VS Code extension itself (as opposed to quarto-cli) and I can investigate further.

**Comment by jooyoungseo** [comment] 2023-07-07 11:30
@jjallaire and @cscheid -- I have confirmed that this issue has been resolved after installing yesterday's Quarto prerelease! Thanks!

**Comment by cscheid** [comment] 2023-07-07 20:52
This should be fixed on the latest commit of quarto on `main`. A new 1.4 pre-release build will be out shortly.

**Closed** 2023-07-07 20:52 UTC
