### ISSUE TITLE
Cross-reference to book chapter uses chapter title instead of Chapter + number

### ISSUE THREAD

**Issue by ecodiv** [quarto-dev/quarto#515] opened 2024-08-11 10:24 UTC
## Bug description

When using cross-references to a chapter, the number + chapter title is used instead of chapter + chapter number

## Steps to reproduce

1. Create a new book (use the default template in RStudio).
2. On the intro page, add a label to the main heading, e.g., `#sec-introduction`
3. On the first page (index.qmd) ad a reference to the introduction chapter by adding, somewhere in the text, e.g., `see also @sec-introduction`
4. Render the page to html.

## Expected behaviour

The reference to the introduction chapter should render like:  `See also Chapter 1` 

## Actual behavior

It shows the chapter number + title 

![image](https://github.com/user-attachments/assets/c283c67a-d1f0-4873-9057-091557f30349)

## Enviroment

- Quarto 1.5.56
- IDE: RStudio 2024.08.0 Build 351
- OS: Ubuntu 24.04

## Quarto check output

````
Quarto 1.5.56
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.56
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.3
      Path: /tmp/RtmpbGZLnU/rstudio/terminal/python3
      Jupyter: 5.3.2
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /usr/lib/R
      LibPaths:
        - /home/paulo/R/x86_64-pc-linux-gnu-library/4.4
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
````

**Comment by ecodiv** [comment] 2024-08-11 11:04
I did some further testing, this only happens when using a cross-reference to a chapter or paragraph from within a chapter that has no numbering, i.e., with `{.unnumbered}` after the chapter title.

**Comment by cscheid** [comment] 2024-08-15 15:35
(For future reference, the repository for the quarto command-line tool is https://github.com/quarto-dev/quarto-cli)

This is a duplicate of https://github.com/quarto-dev/quarto-cli/issues/8514

**Closed by cscheid** 2024-08-15 15:35 UTC
