### ISSUE TITLE
Python UserWarning  not suppressed with warning:false

### ISSUE THREAD

**Issue by ldecicco-USGS** [quarto-dev/quarto#125] opened 2023-03-25 13:52 UTC
I'm using the following python chunk in a Quarto document:

````
```{python}
#| warning: false
#| echo: true
import dataretrieval.nwis as nwis
df = nwis.get_record(sites='03339000', service='dv', 
                     start='2017-12-31', parameterCd='00060')
df.shape[0]
```
````

When I render the doc, it looks like this:

![image](https://user-images.githubusercontent.com/1105215/227721212-5cd3f734-7997-4119-bda6-6e065047a969.png)

I would expect not to see the UserWarning with the `warning: false` flag. Is this a bug or is do Python warnings work different than R warnings?

**Comment by jjallaire** [comment] 2023-03-25 14:40
I am not able to reproduce this -- I don't see any warnings when rendering this document:

````markdown
---
title: "Warnings"
format: html
---

```{python}
#| warning: false
#| #| echo: true
import warnings
warnings.warn("a warning")
1 + 1
```

```{python}
#| warning: false
#| echo: true
import dataretrieval.nwis as nwis
df = nwis.get_record(sites='03339000', service='dv', 
                     start='2017-12-31', parameterCd='00060')
df.shape[0]
```
````

I do however see a warning when I "Run Cell" in VS Code:

<img width="661" alt="Screen Shot 2023-03-25 at 10 39 29 AM" src="https://user-images.githubusercontent.com/104391/227724012-75f4fbbe-2a3a-43a5-8e83-8c80231b3e37.png">

This behavior isn't controlled by Quarto though and might require more explicit Python code (e.g. https://noteable.io/blog/disable-warnings-in-jupyter/)

**Comment by ldecicco-USGS** [comment] 2023-03-25 16:19
I'm seeing the warnings when I mix R and Python:

````
---
title: "Warnings"
format: html
---

```{python}
#| warning: false
#| #| echo: true
import warnings
warnings.warn("a warning")
1 + 1
```


```{r}
#| warning: false
#| echo: true
library(dataRetrieval)
df <- readNWISdv('03339000', '00060', '2020-01-01')
nrow(df)
```


```{python}
#| warning: false
#| echo: true
import dataretrieval.nwis as nwis
df = nwis.get_record(sites='03339000', service='dv', 
                     start='2017-12-31', parameterCd='00060')
df.shape[0]
```

````


![image](https://user-images.githubusercontent.com/1105215/227729238-326c3719-14ac-4b17-9814-475b9703bf03.png)

**Comment by ldecicco-USGS** [comment] 2023-03-25 19:14
I forgot to mention, you are right that ignoring the warnings via python does work throughout the doc, even when mixing R and python:

````
```{python}
#| echo: false
import warnings
warnings.filterwarnings('ignore')
```
````

**Comment by jjallaire** [comment] 2023-03-26 11:31
Okay, it looks like this is an issue with the reticulate knitr engine.  @t-kalinowski The following Rmd document exhibits the same issue (the knitr `warning=FALSE` option is not respected for Python chunks): 

````
---
title: "Warnings"
output: html_document
---

```{python, warning=FALSE}
import warnings
warnings.warn("a warning")
1 + 1
```
````

I'm going to close this issue here (hopefully the issue will then be resolved over in reticulate)

**Closed by jjallaire** 2023-03-26 11:31 UTC

**Comment by t-kalinowski** [comment] 2023-03-27 16:23
Now fixed on the development version of reticulate. You can install with:
```r
remotes::install_github("rstudio/reticulate")
```
