### ISSUE TITLE
Typst format uses same symbols in nested bullet lists

### ISSUE THREAD

**Issue by wangzk** [quarto-dev/quarto#456] opened 2024-05-31 07:58 UTC
The typst format does not produce correct nested list: the symbols before items on different levels are same. In the other formats (like pdf), the symbols are different.

```{quarto}
---
title: Test Document
---

* Level 1
  + Level 2
    - Level 3 
* Level 1
  + Level 2
    - Level 3 
* Level 1
```

The following is the pdf file produced by typst:

<img width="482" alt="image" src="https://github.com/quarto-dev/quarto/assets/2674020/72cdc8b0-ae43-4a67-af75-6b8c1644655a">

The symbols before each level are same.

The following is the pdf file produced by latex:

<img width="654" alt="image" src="https://github.com/quarto-dev/quarto/assets/2674020/e15669fd-52e5-455b-896c-65ca2b2a8e7f">

The *default* behavior of nested bullet lists in typst (https://typst.app/docs/reference/model/list/) also uses different symbols on different levels:

<img width="630" alt="image" src="https://github.com/quarto-dev/quarto/assets/2674020/d463e9ec-7ab7-4105-a505-650beca22738">

**Comment by cscheid** [comment] 2024-05-31 16:06
I can't reproduce that:

<img width="485" alt="image" src="https://github.com/quarto-dev/quarto/assets/285675/d16c3633-8845-49e0-91c8-8e9d52c7e2c0">

Quarto doesn't do anything special here, so I think what's going on is that you're running an older version of Quarto, which bundled an older version of Typst, which didn't have different symbols for different list nesting. I'm going to go ahead and close this one, but feel free to reopen if you can provide a reproducible example using Quarto 1.5.39 or later.

**Closed by cscheid** 2024-05-31 16:06 UTC
