### ISSUE TITLE
Quarto preview broken (command not found) when using bundled Quarto and Pyenv

### ISSUE THREAD

**Issue by testlabauto** [quarto-dev/quarto#517] opened 2024-08-15 18:35 UTC
I have a Positron smoke test that opens a [sample RMD file](https://github.com/posit-dev/qa-example-content/blob/main/workspaces/basic-rmd-file/basicRmd.rmd) and then attempts to preview it with cmd+shift+k.  It is failing to find the bundled Quarto installation and in the Positron terminal I am seeing:

```
quarto preview /Users/christophermead/posit/qa-example-content/workspaces/basic-rmd-file/basicRmd.rmd --no-browser --no-watch-inputs --outpu4wtc0000gn/T/tmp-40396-zJDD9eqpFeVs --embed-resources
(base) ➜  qa-example-content quarto preview /Users/christophermead/posit/qa-example-content/workspaces/basic-rmd-file/basicRmd.rmd --no-brow
ser --no-watch-inputs --output-dir /var/folders/rc/l24758015ggb5438npy04wtc0000gn/T/tmp-40396-zJDD9eqpFeVs --embed-resources
zsh: command not found: quarto
```

Discussing this with @jmcphers, he has noted that we need to adjust the PATH in the created Quarto Preview terminal so that the terminal can access the Quarto installation even if it is not on the PATH.

**Comment by cderv** [comment] 2024-08-15 19:37
Could it be related to latest addition by @jmcphers ? 
- https://github.com/quarto-dev/quarto/pull/503

? 

This is quite recent and would require very latest version of extension, and we may need to build a new one if not already.

**Comment by jmcphers** [comment] 2024-08-15 19:46
Version 114 of the extension has change #503, and Positron bundles version 114. 

If I'm reading the code correctly, though, this would be a problem on any system that doesn't have quarto on the path. That includes e.g. quarto when found only inside an RStudio installation.

**Comment by jmcphers** [comment] 2024-08-28 17:51
I spent some time looking into this. It looks like the Quarto extension does indeed _try_ to add `quarto` to the Path, which is pretty close to the change I had intended to make.

https://github.com/quarto-dev/quarto/blob/8ec3fc890b3e279b8be697aaa02d2b8ac5812337/apps/vscode/src/main.ts#L71-L75

The _Terminal: Show Environment Contributions_ command shows that this works as it's supposed to:

<img width="764" alt="image" src="https://github.com/user-attachments/assets/61f01db6-7099-4eb1-bb79-b86e5c5ce28f">

And in fact, I can't repro this problem at all with the latest build of Positron; quarto does get added to the path and it works fine.

**Comment by jonvanausdeln** [comment] 2024-08-28 18:32
I just tried with the latest build of Positron ([2024.08.0-77](https://github.com/posit-dev/positron-builds/releases/tag/2024.08.0-77) on Windows and it doesn't find Quarto.
* Uninstalled all quarto versions
* Uninstalled all Positron
* Installed [2024.08.0-77](https://github.com/posit-dev/positron-builds/releases/tag/2024.08.0-77)
* Open .qmd file, and try to preview

```
C:\Users\JonVanausdeln\source\qa-example-content [main ≡]> quarto preview c:/Users/JonVanausdeln/source/qa-example-content/workspaces/quarto_basic/quarto_basic.qmd --no-browser --no-watch-inputs --output-dir C:\Users\JONVAN~1\AppData\Local\Temp\tmp-32232-hHeUVdON8Tb2 --embed-resources
quarto: The term 'quarto' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by jmcphers** [comment] 2024-08-28 18:45
@jonvanausdeln what does the _Terminal: Show Environment Contributions_ command show for you?

**Comment by jonvanausdeln** [comment] 2024-08-28 18:55
> @jonvanausdeln what does the _Terminal: Show Environment Contributions_ command show for you?

```
## Extension: quarto.quarto

- `PATH=;c:\Program Files\Positron\resources\app\quarto\bin;${env:PATH}`
```

**Comment by testlabauto** [comment] 2024-08-28 19:29
Unless I am doing something wrong, this also still happens on OSX:

```
quarto preview /Users/christophermead/posit/qa-example-content/workspaces/basic-rmd-file/basicRmd.rmd --no-browser --no-watch-inputs --output-dir /var/folders/rc/l24758015ggb5438npy04wtc0000gn/T/tmp-90360-EkbYZOl8WvcB --embed-resources
(base) ➜  qa-example-content quarto preview /Users/christophermead/posit/qa-example-content/workspaces/basic-rmd-file/basicRmd.rmd --no-browser --no-watch-inputs --output-dir /var/folders/rc/
l24758015ggb5438npy04wtc0000gn/T/tmp-90360-EkbYZOl8WvcB --embed-resources
zsh: command not found: quarto
(base) ➜  qa-example-content git:(cmead/add-devtools) 
```
Terminal: Show Environment Contributions
```
# Terminal Environment Changes

## Extension: quarto.quarto

- `PATH=:/Applications/Positron.app/Contents/Resources/app/quarto/bin:${env:PATH}`
```

**Comment by jmcphers** [comment] 2024-08-28 23:09
@jonvanausdeln are you using Pyenv by any chance? and can you show what your `$PATH` looks like after running `quarto` like Chris did? 

I noticed that @testlabauto's `$PATH` (which is broken) has a whole bunch of `.pyenv` stuff on it, but mine (which is working) doesn't. So I tried switching to a pyenv-managed Python, and ... bam! I am suddenly able to reproduce this locally. It looks like pyenv is somehow dropping the Quarto entry from the `$PATH` when it's pushing its own shims to the front.

**Comment by jonvanausdeln** [comment] 2024-08-29 15:07
@jmcphers , yes I am using pyenv

Also, here is the `$PATH` output.. I don't see quarto actually being added.
```
C:\Users\JonVanausdeln\source\qa-example-content [main ≡]> quarto preview c:/Users/JonVanausdeln/source/qa-example-content/workspaces/quarto_basic/quarto_basic.qmd --no-browser --no-watch-inputs --output-dir C:\Users\JONVAN~1\AppData\Local\Temp\tmp-7280-Jxe7thU55mC3 --embed-resources
quarto: The term 'quarto' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
C:\Users\JonVanausdeln\source\qa-example-content [main ≡]> $env:path -split ";"
C:\Users\JonVanausdeln\.pyenv\pyenv-win\versions\3.12.2
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\WINDOWS\System32\OpenSSH\
C:\Program Files\dotnet\
C:\ProgramData\chocolatey\bin
C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\
C:\Program Files\Git\cmd
%NVM_HOME%
%NVM_SYMLINK%
C:\Program Files\rig
C:\Program Files\R\bin
C:\Program Files\PowerShell\7\
C:\Program Files\Positron\bin
C:\Users\JonVanausdeln\scoop\shims
C:\Users\JonVanausdeln\.pyenv\pyenv-win\bin
C:\Users\JonVanausdeln\.pyenv\pyenv-win\shims
C:\Users\JonVanausdeln\.pyenv\pyenv-win\bin
C:\Users\JonVanausdeln\.pyenv\pyenv-win\shims
C:\Users\JonVanausdeln\.pyenv\pyenv-win\bin
C:\Users\JonVanausdeln\.pyenv\pyenv-win\shims
C:\Users\JonVanausdeln\.pyenv\pyenv-win\bin
C:\Users\JonVanausdeln\.pyenv\pyenv-win\shims
C:\Users\JonVanausdeln\AppData\Local\Microsoft\WindowsApps    
C:\Users\JonVanausdeln\AppData\Roaming\nvm
C:\Program Files\nodejs
C:\Users\JonVanausdeln\.pyenv\pyenv-win\bin
C:\Users\JonVanausdeln\.pyenv\pyenv-win\shims
C:\Users\JonVanausdeln\AppData\Local\Programs\Microsoft VS Code\bin
C:\Program Files\Graphviz\bin
C:\Users\JonVanausdeln\AppData\Local\GitHubDesktop\bin        
C:\Users\JonVanausdeln\AppData\Local\Pandoc\
C:\Program Files\PowerShell\7
C:\Users\JonVanausdeln\.pyenv\pyenv-win\versions\3.12.2       
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\WINDOWS\System32\OpenSSH\
C:\Program Files\dotnet\
C:\ProgramData\chocolatey\bin
C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\
C:\Program Files\Git\cmd
%NVM_HOME%
%NVM_SYMLINK%
C:\Program Files\rig
C:\Program Files\R\bin
C:\Program Files\PowerShell\7\
C:\Program Files\Positron\bin
C:\Users\JonVanausdeln\scoop\shims
C:\Users\JonVanausdeln\.pyenv\pyenv-win\bin
C:\Users\JonVanausdeln\.pyenv\pyenv-win\shims
C:\Users\JonVanausdeln\.pyenv\pyenv-win\bin
C:\Users\JonVanausdeln\.pyenv\pyenv-win\shims
C:\Users\JonVanausdeln\.pyenv\pyenv-win\bin
C:\Users\JonVanausdeln\.pyenv\pyenv-win\shims
C:\Users\JonVanausdeln\.pyenv\pyenv-win\bin
C:\Users\JonVanausdeln\.pyenv\pyenv-win\shims
C:\Users\JonVanausdeln\AppData\Local\Microsoft\WindowsApps    
C:\Users\JonVanausdeln\AppData\Roaming\nvm
C:\Program Files\nodejs
C:\Users\JonVanausdeln\.pyenv\pyenv-win\bin
C:\Users\JonVanausdeln\.pyenv\pyenv-win\shims
C:\Users\JonVanausdeln\AppData\Local\Programs\Microsoft VS Code\bin
C:\Program Files\Graphviz\bin
C:\Users\JonVanausdeln\AppData\Local\GitHubDesktop\bin        
C:\Users\JonVanausdeln\AppData\Local\Pandoc\
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\WINDOWS\System32\OpenSSH\
C:\Program Files\dotnet\
C:\ProgramData\chocolatey\bin
C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\
%NVM_HOME%
%NVM_SYMLINK%
C:\Program Files\rig
C:\Program Files\R\bin
C:\Program Files\PowerShell\7\
C:\Program Files\Positron\bin
C:\Users\JonVanausdeln\scoop\shims
C:\Users\JonVanausdeln\.pyenv\pyenv-win\bin
C:\Users\JonVanausdeln\.pyenv\pyenv-win\shims
C:\Users\JonVanausdeln\.pyenv\pyenv-win\bin
C:\Users\JonVanausdeln\.pyenv\pyenv-win\shims
C:\Users\JonVanausdeln\.pyenv\pyenv-win\bin
C:\Users\JonVanausdeln\.pyenv\pyenv-win\shims
C:\Users\JonVanausdeln\.pyenv\pyenv-win\bin
C:\Users\JonVanausdeln\.pyenv\pyenv-win\shims
C:\Users\JonVanausdeln\AppData\Local\Microsoft\WindowsApps
C:\Users\JonVanausdeln\AppData\Roaming\nvm
C:\Program Files\nodejs
C:\Users\JonVanausdeln\.pyenv\pyenv-win\bin
C:\Users\JonVanausdeln\.pyenv\pyenv-win\shims
C:\Users\JonVanausdeln\AppData\Local\Programs\Microsoft VS Code\bin
C:\Program Files\Graphviz\bin
C:\Users\JonVanausdeln\AppData\Local\GitHubDesktop\bin
C:\Users\JonVanausdeln\AppData\Local\Pandoc\
```

**Comment by jmcphers** [comment] 2024-08-29 15:26
>  I don't see quarto actually being added.

It looks to me like the problem is that quarto _is_ added (we confirmed that by looking at your Environment Contributions)... but Pyenv removes it when the Terminal starts (it organizes the `$PATH` to put its shims first). It is not clear to me why it's dropping Quarto but both @testlabauto and myself have confirmed that the problem only happens when Pyenv modifies the PATH.

Some possible routes forward:
- have the Quarto extension emit the full path to the Quarto executable so that it is immune to this behavior (I'm not actually sure whether or not this will work since there are other executables in the `bin` folder that Quarto may assume to be on the path?)
- figure out what is causing Pyenv to discard our PATH entry and change the Quarto extension to avoid the behavior (e.g. could it be that we're adding a leading separator and that confuses Pyenv?)
- figure out a way to put our PATH entry _back_ after Pyenv removes it (e.g. by emitting a command before the Quarto render happens)
- [run away from home and live in the woods](https://www.wikihow.com/Run-Away-from-Home-and-Live-in-the-Woods)

**Comment by isabelizimm** [comment] 2024-11-21 21:15
It turns out, this PATH addition was being overridden by `positron-python`. Fixed in Positron! See PR for more details: https://github.com/posit-dev/positron/pull/5354

**Closed by isabelizimm** 2024-11-21 21:15 UTC
