### ISSUE TITLE
Quarto does not use native photo rotation (EXIF Data)

### ISSUE THREAD

**Issue by SilasK** [quarto-dev/quarto#334] opened 2023-12-13 20:44 UTC
I took a photo with my camera.

The photo is automatically displayed in the native rotation. 

When I include the image in a quarto document with simple:

```
![](img/PC130002.JPG)
```

Only the HTML output gets the rotation right. docx and HTML display a wrongly rotated image.

I don't know which metadata this native rotation is based on, nor how to correct it. Even more so if it is not consistent between the formats. 

<img width="835" alt="Screenshot 2023-12-13 at 21 37 02" src="https://github.com/quarto-dev/quarto/assets/7523034/e36ff441-1f5c-4f2f-bc3d-67ed986179fe">

The docx preview shows the correct orientation, but the real document doesn't. This is really head-turning.

<img width="535" alt="Screenshot 2023-12-13 at 21 37 02" src="https://github.com/quarto-dev/quarto/assets/7523034/256bdd8e-1ade-4b72-a6ba-701ea1663c57">

**Comment by SilasK** [comment] 2023-12-13 20:44
I use Quarto v 1.4.506

**Comment by SilasK** [comment] 2023-12-13 20:48
As I understand it's related to the EXIF Data, which is only respect by HTML renderer.

**Comment by cscheid** [comment] 2023-12-13 20:57
> Only the HTML output gets the rotation right. docx and HTML display a wrongly rotated image.

Do you mean "docx and PDF display a wrongly rotated image"?

In that case, I think these are Microsoft Word and pdflatex bugs, not quarto bugs. We unfortunately can't control the output generation at this level (because we would need an API for detecting EXIF in sufficient generality, as well as rotating the image explicitly). We can't do that portably across the image formats available. I'm going to go ahead and close this one, but if you think that's not what's happening, please feel free to reopen!

**Closed by cscheid** 2023-12-13 20:57 UTC

**Comment by jonassmedegaard** [comment] 2024-02-09 05:39
Although indeed this is a limitation in LaTeX (but arguably not a bug, only a feature request: It can place images but cannot take into account EXIF metadata embedded in images), there is a possibility for quarto to handle this:

Quarto can optionally (and perhaps suggested as a runtime warning when targets known to not support EXIF metadata is involved), call "exiftran -ia $_site/path/to/each/target/EXIF-using/image", to losslessly pre-rotate the image and adjust its EXIF data to no longer hint a need for rotation.
